apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-demo
  labels:
    project: roboshop
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                  - us-east-1b
  containers:
    - name: nginx
      image: nginx
