apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-demo
  labels:
    project: roboshop
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                  - us-east-1b
              - key: disktype
                operator: In
                values:
                  - ssd
      preferredDuringSchedulingIgnoredDuringExecution:

      #More weight will consider the order of execution 
        - weight: 10
          preference:
            matchExpressions:
              - key: project
                operator: In
                values:
                  - roboshop
        - weight: 1
          preference:
            matchExpressions:
              - key: project
                operator: In
                values:
                  - roboshop
  containers:
  containers:
    - name: nginx
      image: nginx
