apiVersion: apps/v1
kind: Deployment
metadata:
  name: seclector
  labels:
    purpose: dep
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: dep
      project: roboshop
  template:
    metadata:
      labels:
        purpose: dep
        project: roboshop
    spec:
      containers:
        - name: nginx
          image: nginx
